AWSTemplateFormatVersion: 2010-09-09

# Physical Layer
Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16  # Default CIDR block for the VPC
  Az1:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-2a  # Default Availability Zone
  SubnetCidrBlocks:
    Description: "A list of CIDR blocks for subnets"
    Type: CommaDelimitedList
    Default: >
      10.0.0.0/24, 
      10.0.4.0/24,
      10.0.8.0/24,
      10.0.12.0/24,
      10.0.16.0/24,
      10.0.20.0/24,
      10.0.24.0/24,
      10.0.28.0/24,
      10.0.32.0/24
  Az2:
    Description: "Availability Zones for subnets"
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "us-east-2b"
  Az3:
    Description: "Additional Availability Zones for subnets"
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "us-east-2c"



# Create the VPC resource using the specified parameters.
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock  # Use the VpcCidrBlock parameter value
      EnableDnsSupport: true
      EnableDnsHostnames: true
