AWSTemplateFormatVersion: 2010-09-09
# Physical Layer
Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16  # Default CIDR block for the VPC
  Az1:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-2a  # Default Availability Zone
  SubnetCidrBlocks:
    Description: "A list of CIDR blocks for subnets"
    Type: CommaDelimitedList
    Default: >
      10.0.0.0/24, 
      10.0.4.0/24,
      10.0.8.0/24,
      10.0.12.0/24,
      10.0.16.0/24,
      10.0.20.0/24,
      10.0.24.0/24,
      10.0.28.0/24,
      10.0.32.0/24
  Az2:
    Description: "Availability Zones for subnets"
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "us-east-2b"
  Az3:
    Description: "Additional Availability Zones for subnets"
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "us-east-2c"

# Data Link Layer (VPC and Subnets)
# Create the VPC resource using the specified parameters.
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock  # Use the VpcCidrBlock parameter value
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC
  PublicSubnet1:
   Type: AWS::EC2::Subnet
   Properties:
      AvailabilityZone: !Ref Az1
      CidrBlock: !Select [0, !Ref SubnetCidrBlocks] # Use the first CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PublicSubnet1  # Name tag for identification in AWS Console
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az2
      CidrBlock: !Select [1, !Ref SubnetCidrBlocks] # Use the second CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PublicSubnet2  # Name tag for identification in AWS Console
  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az3
      CidrBlock: !Select [2, !Ref SubnetCidrBlocks] # Use the third CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PublicSubnet3  # Name tag for identification in AWS Console
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az1
      CidrBlock: !Select [3, !Ref SubnetCidrBlocks]  # Use the fourth CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrivateSubnet1  # Name tag for identification in AWS Console        
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az2
      CidrBlock: !Select [4, !Ref SubnetCidrBlocks]  # Use the fifth CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrivateSubnet2  # Name tag for identification in AWS Console        
  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az3
      CidrBlock: !Select [5, !Ref SubnetCidrBlocks]  # Use the sixth CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrivateSubnet3  # Name tag for identification in AWS Console        
  PrivateDBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az1
      CidrBlock: !Select [6, !Ref SubnetCidrBlocks]  # Use the seventh CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrivateDBSubnet1  # Name tag for identification in AWS Console
  PrivateDBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az2
      CidrBlock: !Select [7, !Ref SubnetCidrBlocks]  # Use the eighth CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrivateDBSubnet2  # Name tag for identification in AWS Console 
  PrivateDBSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az3
      CidrBlock: !Select [8, !Ref SubnetCidrBlocks]  # Use the nineth CIDR block from SubnetCidrBlocks
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrivateDBSubnet3  # Name tag for identification in AWS Console        
               
        